### ISSUE TITLE
Custom labels for `nice_fit()`

### ISSUE THREAD

**Issue by Buedenbender** [rempsyc/lavaanExtra#8]
Hi Rémi,

this package has really grown on me and I think it has some nice unique benefits.
A small suggestion for an improvement, I would like to have the ability to supply custom
names for the `nice_fit()` table.

Currently I am using this workaround (which is really not a proper way to name your objects / variables like this 🤔):
```
# Fitting th models ------------------------------------------------------
`CFA 1 Factor` <- cfa(model = model1, data = dataset, estimator = "DWLS")
`CFA 2 Factor` <- cfa(model = model2, data = dataset, estimator = "DWLS")
`CFA 3 Factor` <- cfa(model = model3, data = dataset, estimator = "DWLS")


# Extracing the metrics -------------------------------------------------------
nice_fit(`CFA 1 Factor`, `CFA 2 Factor`, `CFA 3 Factor`, nice_table = T)
```

**Tasks:** 

- [x] Add a `label` argument to the function
- [ ] Add a unit test length(label) = number of lavaan/fit objects
- [x] Integrate the labels in the table

**Priority:**

Very low, it's just a convenience thing. I could also edit the column in word, or just use _

**Comment by rempsyc** [comment]
Thanks! Will look into it!

**Comment by Buedenbender** [comment]
That was fast!!!
Nice will you merge it via PR?

**Comment by rempsyc** [comment]
I didn't use a PR, I pushed the changes directly, so it is already the lastest version! Just have to install it again from GitHub
